import { FORMAT_GREGORIAN, FORMAT_FRENCH_REPUBLICAN, parseDate, FORMAT_UNKNOWN, findMonth } from "./dateParser";

describe('parseDate', () => {
    const testSet = [
        ['primidi 1 vendémiaire an I (1)', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['duodi 2 vendémiaire an I (1)', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['tridi 3 vendémiaire an I (1)', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quartidi 4 vendémiaire an I (1)', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 5 vendémiaire an I (1)', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['sextidi 6 vendémiaire an I (1)', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['septidi 7 vendémiaire an I (1)', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['octidi 8 vendémiaire an I (1)', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['nonidi 9 vendémiaire an I (1)', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['décadi 10 vendémiaire an I (1)', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['primidi 11 vendémiaire an II (2)', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['septidi 17 brumaire an III (3)', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['nonidi 29 frimaire an IV (4)', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['décadi 30 nivôse an V (5)', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['duodi 22 pluviôse an VI (6)', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 ventôse an VII (7)', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 germinal an VIII (8)', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 floréal an IX (9)', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 prairial an X (10)', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 messidor an XI (11)', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 thermidor an XII (12)', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 15 fructidor an XIII (13)', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['primidi 1 jours comp. an XIV (14)', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['duodi 2 jours comp. an XV (15)', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['tridi 3 jours comp. an XVI (16)', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quartidi 4 jours comp. an XVII (17)', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['quintidi 5 jours comp. an XVIII (18)', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['sextidi 6 jours comp. an XI (11)', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['septidi 17 nivôse an CCXXXI (231)', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vendémiaire an I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vendémiaire an I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vendémiaire an I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vendémiaire an I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vendémiaire an I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vendémiaire an I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vendémiaire an I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vendémiaire an I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vendémiaire an I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vendémiaire an I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vendémiaire an II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 brumaire an III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 frimaire an IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 nivôse an V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pluviôse an VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 ventôse an VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 germinal an VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 floréal an IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 prairial an X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 messidor an XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 thermidor an XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fructidor an XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 jours comp. an XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jours comp. an XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jours comp. an XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jours comp. an XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jours comp. an XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jours comp. an XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 nivôse an CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vendémiaire an I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vendémiaire an I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vendémiaire an I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vendémiaire an I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vendémiaire an I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vendémiaire an I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vendémiaire an I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vendémiaire an I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vendémiaire an I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vendémiaire an 1', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vendémiaire an 2', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 brumaire an 3', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 frimaire an 04', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 nivôse an 5', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pluviôse an 6', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 ventôse an 07', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 germinal an 8', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 floréal an 09', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 prairial an 10', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 messidor an 11', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 thermidor an 12', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fructidor an 13', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 jours comp. an 14', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jours comp. an 15', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jours comp. an 16', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jours comp. an 17', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jours comp. an 18', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jours comp. an 11', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 nivôse an 231', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vendemiaire I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vendemiaire I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vendemiaire I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vendemiaire I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vendemiaire I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vendemiaire I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vendemiaire I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vendemiaire I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vendemiaire I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vendemiaire I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vendemiaire II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 brumaire III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 frimaire IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 nivose V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pluviose VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 ventose VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 germinal VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 floreal IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 prairial X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 messidor XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 thermidor XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fructidor XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 jours supp XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jours supp XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jours supp XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jours supp XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jours supp XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jours supp XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 nivose CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vend I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vend I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vend I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vend I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vend I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vend I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vend I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vend I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vend I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vend I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vend II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 bru III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 fri IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 niv V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pluv VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 vent VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 germ VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 flor IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 prair X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 mess XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 therm XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fruc XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 supp XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 supp XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 supp XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 comp XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 comp XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 comp XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 niv CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vend 1', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vend 1', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vend 1', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vend 1', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vend 1', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vend 1', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vend 1', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vend 1', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vend 1', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vend 1', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vend 2', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 bru 3', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 fri 4', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 niv 5', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pluv 6', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 vent 7', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 germ 8', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 flor 9', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 prair 10', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 mess 11', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 therm 12', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fruc 13', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 supp 14', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 supp 15', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 supp 16', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 comp 17', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 comp 18', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 comp 11', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 niv 231', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 vd I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 vd I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 vd I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 vd I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 vd I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 vd I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7 vd I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8 vd I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9 vd I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10 vd I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11 vd II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 br III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29 fr IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30 ni V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22 pl VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 vt VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 gr VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 fl IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 pr X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 ms XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 th XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15 ft XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 sp XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 sp XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jc XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 cp XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 cp XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 sp XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17 niv CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-01', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-02', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-03', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-04', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-05', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-06', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-07', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-08', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-09', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-01-10', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['II-01-11', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['III-02-17', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['IV-03-29', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['V-04-30', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VI-05-22', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VII-06-15', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VIII-07-15', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['IX-08-15', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['X-09-15', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XI-10-15', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XII-11-15', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XIII-12-15', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XIV-13-01', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XV-13-02', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVI-13-03', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVII-13-04', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVIII-13-05', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XI-13-06', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['CCXXXI-04-17', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-1', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-2', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-3', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-4', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-5', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-6', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-7', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-8', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-9', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['I-1-10', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['II-1-11', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['III-2-17', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['IV-3-29', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['V-4-30', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VI-5-22', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VII-6-15', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['VIII-7-15', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['IX-8-15', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['X-9-15', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XI-10-15', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XII-11-15', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XIII-12-15', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XIV-13-1', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XV-13-2', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVI-13-3', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVII-13-4', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XVIII-13-5', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['XI-13-6', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['CCXXXI-4-17', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1/1/I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2/1/I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3/1/I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4/1/I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5/1/I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6/1/I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['7/1/I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['8/1/I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['9/1/I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10/1/I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11/1/II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17/2/III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29/3/IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30/4/V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22/5/VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/6/VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/7/VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/8/IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/9/X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/10/XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/11/XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/12/XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1/13/XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2/13/XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3/13/XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4/13/XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5/13/XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6/13/XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17/4/CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['01/01/I', { year: 1, month: 1, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['02/01/I', { year: 1, month: 1, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['03/01/I', { year: 1, month: 1, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['04/01/I', { year: 1, month: 1, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['05/01/I', { year: 1, month: 1, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['06/01/I', { year: 1, month: 1, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['07/01/I', { year: 1, month: 1, day: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        ['08/01/I', { year: 1, month: 1, day: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        ['09/01/I', { year: 1, month: 1, day: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        ['10/01/I', { year: 1, month: 1, day: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        ['11/01/II', { year: 2, month: 1, day: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17/02/III', { year: 3, month: 2, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],
        ['29/03/IV', { year: 4, month: 3, day: 29, format: FORMAT_FRENCH_REPUBLICAN }],
        ['30/04/V', { year: 5, month: 4, day: 30, format: FORMAT_FRENCH_REPUBLICAN }],
        ['22/05/VI', { year: 6, month: 5, day: 22, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/06/VII', { year: 7, month: 6, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/07/VIII', { year: 8, month: 7, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/08/IX', { year: 9, month: 8, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/09/X', { year: 10, month: 9, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/10/XI', { year: 11, month: 10, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/11/XII', { year: 12, month: 11, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['15/12/XIII', { year: 13, month: 12, day: 15, format: FORMAT_FRENCH_REPUBLICAN }],
        ['01/13/XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['02/13/XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['03/13/XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['04/13/XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['05/13/XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['06/13/XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['17/04/CCXXXI', { year: 231, month: 4, day: 17, format: FORMAT_FRENCH_REPUBLICAN }],

        ['1 jour suppl. XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jour suppl. XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jour suppl. XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jour suppl. XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jour suppl. XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jour suppl. XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 jour compl. XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jour compl. XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jour compl. XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jour compl. XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jour compl. XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jour compl. XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 suppl. XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 suppl. XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 suppl. XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 suppl. XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 suppl. XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 suppl. XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 compl. XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 compl. XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 compl. XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 compl. XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 compl. XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 compl XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 supp XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 supp XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 supp XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 supp XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 supp XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 supp XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 comp XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 comp XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 comp XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 comp XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 comp XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 comp XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 js XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 js XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 js XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 js XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 js XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 js XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['1 jc XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['2 jc XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['3 jc XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['4 jc XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['5 jc XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['6 jc XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de la vertu XIV', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour du génie XV', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour du travail XVI', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de l\'opinion XVII', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour des récompenses XVIII', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de la révolution XI', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de la vertu 14', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour du genie 15', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour du travail 16', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de l opinion 17', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour des recompenses 18', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['jour de la revolution 11', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        ['vertu 14', { year: 14, month: 13, day: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        ['genie 15', { year: 15, month: 13, day: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        ['travail 16', { year: 16, month: 13, day: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        ['opinion 17', { year: 17, month: 13, day: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        ['recompenses 18', { year: 18, month: 13, day: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        ['revolution 11', { year: 11, month: 13, day: 6, format: FORMAT_FRENCH_REPUBLICAN }],

        ['lundi 16 mars 2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['mardi 17 mars 2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['mercredi 18 mars 2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['jeudi 19 mars 2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['vendredi 20 mars 2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['samedi 21 mars 2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['dimanche 22 mars 2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['vendredi 11 janvier 2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['mercredi 12 février 2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['lundi 1 mars 2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['jeudi 7 avril 2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['lundi 22 mai 2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['samedi 15 juin 2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['jeudi 31 juillet 2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['mercredi 19 août 2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['vendredi 3 septembre 2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['samedi 12 octobre 1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['vendredi 30 novembre 1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['dimanche 14 décembre 1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['16 mars 2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['17 mars 2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['18 mars 2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['19 mars 2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['20 mars 2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['21 mars 2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['22 mars 2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['11 janvier 2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['12 février 2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['1 mars 2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['7 avril 2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['22 mai 2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['15 juin 2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['31 juillet 2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['19 août 2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['3 septembre 2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['12 octobre 1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['30 novembre 1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['14 décembre 1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['16 mar 2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['17 mar 2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['18 mar 2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['19 mar 2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['20 mar 2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['21 mar 2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['22 mar 2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['11 janv 2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['12 fev 2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['1 mar 2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['7 avr 2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['22 mai 2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['15 juin 2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['31 juil 2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['19 aout 2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['3 sept 2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['12 oct 1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['30 nov 1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['14 dec 1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['16/03/2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['17/03/2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['18/03/2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['19/03/2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['20/03/2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['21/03/2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['22/03/2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['11/01/2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['12/02/2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['01/03/2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['07/04/2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['22/05/2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['15/06/2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['31/07/2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['19/08/2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['03/09/2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['12/10/1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['30/11/1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['14/12/1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['16/3/2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['17/3/2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['18/3/2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['19/3/2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['20/3/2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['21/3/2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['22/3/2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['11/1/2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['12/2/2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['1/3/2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['7/4/2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['22/5/2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['15/6/2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['31/7/2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['19/8/2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['3/9/2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['12/10/1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['30/11/1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['14/12/1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['2020-03-16', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['2020-03-17', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['2020-03-18', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['2020-03-19', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['2020-03-20', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['2020-03-21', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['2020-03-22', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['2019-01-11', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['2020-02-12', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['2021-03-01', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['2022-04-07', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['2023-05-22', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['2024-06-15', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['2025-07-31', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['2026-08-19', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['2027-09-03', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['1793-10-12', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['1798-11-30', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['1800-12-14', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['2020-3-16', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['2020-3-17', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['2020-3-18', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['2020-3-19', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['2020-3-20', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['2020-3-21', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['2020-3-22', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['2019-1-11', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['2020-2-12', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['2021-3-1', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['2022-4-7', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['2023-5-22', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['2024-6-15', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['2025-7-31', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['2026-8-19', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['2027-9-3', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['1793-10-12', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['1798-11-30', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['1800-12-14', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],
        ['16 MAR 2020', { year: 2020, month: 3, day: 16, format: FORMAT_GREGORIAN }],
        ['17 MAR 2020', { year: 2020, month: 3, day: 17, format: FORMAT_GREGORIAN }],
        ['18 MAR 2020', { year: 2020, month: 3, day: 18, format: FORMAT_GREGORIAN }],
        ['19 MAR 2020', { year: 2020, month: 3, day: 19, format: FORMAT_GREGORIAN }],
        ['20 MAR 2020', { year: 2020, month: 3, day: 20, format: FORMAT_GREGORIAN }],
        ['21 MAR 2020', { year: 2020, month: 3, day: 21, format: FORMAT_GREGORIAN }],
        ['22 MAR 2020', { year: 2020, month: 3, day: 22, format: FORMAT_GREGORIAN }],
        ['11 JAN 2019', { year: 2019, month: 1, day: 11, format: FORMAT_GREGORIAN }],
        ['12 FEB 2020', { year: 2020, month: 2, day: 12, format: FORMAT_GREGORIAN }],
        ['01 MAR 2021', { year: 2021, month: 3, day: 1, format: FORMAT_GREGORIAN }],
        ['07 APR 2022', { year: 2022, month: 4, day: 7, format: FORMAT_GREGORIAN }],
        ['22 MAY 2023', { year: 2023, month: 5, day: 22, format: FORMAT_GREGORIAN }],
        ['15 JUN 2024', { year: 2024, month: 6, day: 15, format: FORMAT_GREGORIAN }],
        ['31 JUL 2025', { year: 2025, month: 7, day: 31, format: FORMAT_GREGORIAN }],
        ['19 AUG 2026', { year: 2026, month: 8, day: 19, format: FORMAT_GREGORIAN }],
        ['03 SEP 2027', { year: 2027, month: 9, day: 3, format: FORMAT_GREGORIAN }],
        ['12 OCT 1793', { year: 1793, month: 10, day: 12, format: FORMAT_GREGORIAN }],
        ['30 NOV 1798', { year: 1798, month: 11, day: 30, format: FORMAT_GREGORIAN }],
        ['14 DEC 1800', { year: 1800, month: 12, day: 14, format: FORMAT_GREGORIAN }],

        ['jc 6', { format: FORMAT_UNKNOWN }],
        ['jc an 6', { format: FORMAT_UNKNOWN }],
        ['an 6', { format: FORMAT_UNKNOWN }],
        ['an VI', { format: FORMAT_UNKNOWN }],
        ['1972', { format: FORMAT_UNKNOWN }],
        ['CCXXX', { format: FORMAT_UNKNOWN }],
        ['janvier 1972', { format: FORMAT_UNKNOWN }],
        ['vendémiaire CCXXX', { format: FORMAT_UNKNOWN }],

        ['sextidi 26 messidor an IV (4) avant l\'ère républicaine', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['sextidi 26 messidor an IV avant l\'ère républicaine', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['sextidi 26 messidor IV (4) avant l\'ère républicaine', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['sextidi 26 messidor IV avant l\'ère républicaine', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV av. rép.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 av. rép.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV av. rép.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 av. rép.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV av rep', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 av rep', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV av rép', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 av rep', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV av', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 av', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV av', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 av', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV AR', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 AR', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV AR', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 AR', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV A.R', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 A.R', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV A.R', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 A.R', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an IV A.R.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor an 4 A.R.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor IV A.R.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['26 messidor 4 A.R.', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],

        ['26/10/[IV]', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
        ['[IV]-10-26', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],

        ['26 messidor 4 A.R. poide mank', { year: -3, month: 10, day: 26, format: FORMAT_FRENCH_REPUBLICAN }],
    ]
    for (const [inputData, expectedResult] of testSet) {
        test(`should return ${JSON.stringify(expectedResult)} when provided with "${inputData}"`, () => {
            const actualResult = parseDate(inputData)
            expect(actualResult).toEqual(expectedResult)
        })
    }
})

describe('findMonth', () => {
    const testSet = [
        [{ part: 'jan', format: undefined }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'feb', format: undefined }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'mar', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'apr', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'may', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'jun', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'jul', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'aug', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'sep', format: undefined }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'oct', format: undefined }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'nov', format: undefined }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'dec', format: undefined }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'mar', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'avr', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'mai', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'juin', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'juil', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'aou', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'aoû', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'août', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'aôut', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'âout', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'janvier', format: undefined }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'février', format: undefined }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'mars', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'avril', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'mai', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'juin', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'juillet', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'août', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'septembre', format: undefined }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'octobre', format: undefined }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'novembre', format: undefined }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'décembre', format: undefined }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'JAN', format: undefined }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'FEB', format: undefined }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'MAR', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'APR', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAY', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUN', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUL', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AUG', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'SEP', format: undefined }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'OCT', format: undefined }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'NOV', format: undefined }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'DEC', format: undefined }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'MAR', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'AVR', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAI', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIN', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIL', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AOU', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'AOÛ', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'AOÛT', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'AÔUT', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'ÂOUT', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'JANVIER', format: undefined }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'FÉVRIER', format: undefined }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'MARS', format: undefined }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'AVRIL', format: undefined }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAI', format: undefined }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIN', format: undefined }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUILLET', format: undefined }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AOÛT', format: undefined }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'SEPTEMBRE', format: undefined }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'OCTOBRE', format: undefined }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'NOVEMBRE', format: undefined }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'DÉCEMBRE', format: undefined }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'jan', format: FORMAT_GREGORIAN }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'feb', format: FORMAT_GREGORIAN }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'mar', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'apr', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'may', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'jun', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'jul', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'aug', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'sep', format: FORMAT_GREGORIAN }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'oct', format: FORMAT_GREGORIAN }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'nov', format: FORMAT_GREGORIAN }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'dec', format: FORMAT_GREGORIAN }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'mar', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'avr', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'mai', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'juin', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'juil', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'aou', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'aoû', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'août', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'aôut', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'âout', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'janvier', format: FORMAT_GREGORIAN }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'février', format: FORMAT_GREGORIAN }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'mars', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'avril', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'mai', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'juin', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'juillet', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'août', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'septembre', format: FORMAT_GREGORIAN }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'octobre', format: FORMAT_GREGORIAN }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'novembre', format: FORMAT_GREGORIAN }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'décembre', format: FORMAT_GREGORIAN }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'JAN', format: FORMAT_GREGORIAN }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'FEB', format: FORMAT_GREGORIAN }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'MAR', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'APR', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAY', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUN', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUL', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AUG', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'SEP', format: FORMAT_GREGORIAN }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'OCT', format: FORMAT_GREGORIAN }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'NOV', format: FORMAT_GREGORIAN }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'DEC', format: FORMAT_GREGORIAN }, { month: 12, format: FORMAT_GREGORIAN }],

        [{ part: 'MAR', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'AVR', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAI', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIN', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIL', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AOU', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'AOÛ', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'AOÛT', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'AÔUT', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'ÂOUT', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],

        [{ part: 'JANVIER', format: FORMAT_GREGORIAN }, { month: 1, format: FORMAT_GREGORIAN }],
        [{ part: 'FÉVRIER', format: FORMAT_GREGORIAN }, { month: 2, format: FORMAT_GREGORIAN }],
        [{ part: 'MARS', format: FORMAT_GREGORIAN }, { month: 3, format: FORMAT_GREGORIAN }],
        [{ part: 'AVRIL', format: FORMAT_GREGORIAN }, { month: 4, format: FORMAT_GREGORIAN }],
        [{ part: 'MAI', format: FORMAT_GREGORIAN }, { month: 5, format: FORMAT_GREGORIAN }],
        [{ part: 'JUIN', format: FORMAT_GREGORIAN }, { month: 6, format: FORMAT_GREGORIAN }],
        [{ part: 'JUILLET', format: FORMAT_GREGORIAN }, { month: 7, format: FORMAT_GREGORIAN }],
        [{ part: 'AOÛT', format: FORMAT_GREGORIAN }, { month: 8, format: FORMAT_GREGORIAN }],
        [{ part: 'SEPTEMBRE', format: FORMAT_GREGORIAN }, { month: 9, format: FORMAT_GREGORIAN }],
        [{ part: 'OCTOBRE', format: FORMAT_GREGORIAN }, { month: 10, format: FORMAT_GREGORIAN }],
        [{ part: 'NOVEMBRE', format: FORMAT_GREGORIAN }, { month: 11, format: FORMAT_GREGORIAN }],
        [{ part: 'DÉCEMBRE', format: FORMAT_GREGORIAN }, { month: 12, format: FORMAT_GREGORIAN }],


        [{ part: 'jan', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'feb', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'mar', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'apr', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'may', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'jun', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'jul', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'aug', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'sep', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'oct', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'nov', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'dec', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'mar', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'avr', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'mai', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'juin', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'juil', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'aou', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'aoû', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'août', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'aôut', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'âout', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'janvier', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'février', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'mars', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'avril', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'mai', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'juin', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'juillet', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'août', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'septembre', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'octobre', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'novembre', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'décembre', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'JAN', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'FEB', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'MAR', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'APR', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'MAY', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUN', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUL', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AUG', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'SEP', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'OCT', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'NOV', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'DEC', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'MAR', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AVR', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'MAI', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUIN', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUIL', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AOU', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'AOÛ', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AOÛT', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AÔUT', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ÂOUT', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'JANVIER', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'FÉVRIER', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'MARS', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AVRIL', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'MAI', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUIN', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'JUILLET', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'AOÛT', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'SEPTEMBRE', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'OCTOBRE', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'NOVEMBRE', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'DÉCEMBRE', format: FORMAT_FRENCH_REPUBLICAN }, { format: FORMAT_UNKNOWN }],



        [{ part: 'vendémiaire', format: undefined }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'brumaire', format: undefined }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'frimaire', format: undefined }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'nivôse', format: undefined }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pluviôse', format: undefined }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ventôse', format: undefined }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'germinal', format: undefined }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'floréal', format: undefined }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'prairial', format: undefined }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'messidor', format: undefined }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'thermidor', format: undefined }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fructidor', format: undefined }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'complémentaire', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'supplémentaire', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'vend', format: undefined }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'bru', format: undefined }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fri', format: undefined }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'niv', format: undefined }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'plu', format: undefined }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'vent', format: undefined }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ger', format: undefined }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'flo', format: undefined }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pra', format: undefined }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'mes', format: undefined }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'the', format: undefined }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fru', format: undefined }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'compl.', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'suppl.', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'comp', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'supp', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'vd', format: undefined }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'br', format: undefined }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fr', format: undefined }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ni', format: undefined }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pl', format: undefined }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'vt', format: undefined }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ge', format: undefined }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fl', format: undefined }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pr', format: undefined }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ms', format: undefined }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'th', format: undefined }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ft', format: undefined }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'jc', format: undefined }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'gr', format: undefined }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'me', format: undefined }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'tr', format: undefined }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],



        [{ part: 'vendémiaire', format: FORMAT_FRENCH_REPUBLICAN }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'brumaire', format: FORMAT_FRENCH_REPUBLICAN }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'frimaire', format: FORMAT_FRENCH_REPUBLICAN }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'nivôse', format: FORMAT_FRENCH_REPUBLICAN }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pluviôse', format: FORMAT_FRENCH_REPUBLICAN }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ventôse', format: FORMAT_FRENCH_REPUBLICAN }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'germinal', format: FORMAT_FRENCH_REPUBLICAN }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'floréal', format: FORMAT_FRENCH_REPUBLICAN }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'prairial', format: FORMAT_FRENCH_REPUBLICAN }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'messidor', format: FORMAT_FRENCH_REPUBLICAN }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'thermidor', format: FORMAT_FRENCH_REPUBLICAN }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fructidor', format: FORMAT_FRENCH_REPUBLICAN }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'complémentaire', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'supplémentaire', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'vend', format: FORMAT_FRENCH_REPUBLICAN }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'bru', format: FORMAT_FRENCH_REPUBLICAN }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fri', format: FORMAT_FRENCH_REPUBLICAN }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'niv', format: FORMAT_FRENCH_REPUBLICAN }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'plu', format: FORMAT_FRENCH_REPUBLICAN }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'vent', format: FORMAT_FRENCH_REPUBLICAN }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ger', format: FORMAT_FRENCH_REPUBLICAN }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'flo', format: FORMAT_FRENCH_REPUBLICAN }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pra', format: FORMAT_FRENCH_REPUBLICAN }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'mes', format: FORMAT_FRENCH_REPUBLICAN }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'the', format: FORMAT_FRENCH_REPUBLICAN }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fru', format: FORMAT_FRENCH_REPUBLICAN }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'compl.', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'suppl.', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'comp', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'supp', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'vd', format: FORMAT_FRENCH_REPUBLICAN }, { month: 1, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'br', format: FORMAT_FRENCH_REPUBLICAN }, { month: 2, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fr', format: FORMAT_FRENCH_REPUBLICAN }, { month: 3, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ni', format: FORMAT_FRENCH_REPUBLICAN }, { month: 4, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pl', format: FORMAT_FRENCH_REPUBLICAN }, { month: 5, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'vt', format: FORMAT_FRENCH_REPUBLICAN }, { month: 6, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ge', format: FORMAT_FRENCH_REPUBLICAN }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'fl', format: FORMAT_FRENCH_REPUBLICAN }, { month: 8, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'pr', format: FORMAT_FRENCH_REPUBLICAN }, { month: 9, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ms', format: FORMAT_FRENCH_REPUBLICAN }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'th', format: FORMAT_FRENCH_REPUBLICAN }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'ft', format: FORMAT_FRENCH_REPUBLICAN }, { month: 12, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'jc', format: FORMAT_FRENCH_REPUBLICAN }, { month: 13, format: FORMAT_FRENCH_REPUBLICAN }],

        [{ part: 'gr', format: FORMAT_FRENCH_REPUBLICAN }, { month: 7, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'me', format: FORMAT_FRENCH_REPUBLICAN }, { month: 10, format: FORMAT_FRENCH_REPUBLICAN }],
        [{ part: 'tr', format: FORMAT_FRENCH_REPUBLICAN }, { month: 11, format: FORMAT_FRENCH_REPUBLICAN }],



        [{ part: 'vendémiaire', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'brumaire', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'frimaire', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'nivôse', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'pluviôse', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ventôse', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'germinal', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'floréal', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'prairial', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'messidor', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'thermidor', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'fructidor', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'complémentaire', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'supplémentaire', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'vend', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'bru', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'fri', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'niv', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'plu', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'vent', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ger', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'flo', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'pra', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'mes', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'the', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'fru', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'compl.', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'suppl.', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'comp', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'supp', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'vd', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'br', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'fr', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ni', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'pl', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'vt', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ge', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'fl', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'pr', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ms', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'th', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'ft', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'jc', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],

        [{ part: 'gr', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'me', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],
        [{ part: 'tr', format: FORMAT_GREGORIAN }, { format: FORMAT_UNKNOWN }],



        [{ part: 'jui', format: undefined }, { format: FORMAT_UNKNOWN }], // juin ? juillet ?
        [{ part: 'ven', format: undefined }, { format: FORMAT_UNKNOWN }], // vendémiaire ? ventôse ? 
        [{ part: 'gav', format: undefined }, { format: FORMAT_UNKNOWN }],
        [{ part: 'vendredi', format: undefined }, { format: FORMAT_UNKNOWN }], // special case : vendredi starts with "vend" like the abv of "vendémaire", but should not be considered as a month
        [{ part: 'mardi', format: undefined }, { format: FORMAT_UNKNOWN }], // special case : mardi starts with "mar" like the abv of "mars" or "march", but should not be considered as a month
        [{ part: 'av', format: undefined }, { format: FORMAT_UNKNOWN }], // to be sur "av" can't be seen as a month because it mean "before" epoch of the current calendar
    ]
    for (const [inputData, expectedResult] of testSet) {
        test(`should return ${JSON.stringify(expectedResult)} when provided with "${JSON.stringify(inputData)}"`, () => {
            const actualResult = findMonth(inputData)
            expect(actualResult).toEqual(expectedResult)
        })
    }
})